language: py2
script:
  - apt-get install libmysqlclient-dev -y
  - pip install -r py_flask/requirements.txt
  - python py_flask/init_db.py
  - cd py_flask && uwsgi --http-socket=$APP_HOST:$APP_PORT --module=server --callable=app --processes=4 --threads=30
